Repository projectcitybuild/web, pull requests merged in 2019-07, with the labels that each got.

#80 Add usernames to site
  src/app/Entities/Accounts/Models/Account.php
  src/app/Entities/Accounts/Models/UnactivatedAccount.php
  src/app/Entities/Accounts/Repositories/AccountRepository.php
  src/app/Entities/Accounts/Repositories/UnactivatedAccountRepository.php
  src/app/Entities/Accounts/Resources/AccountResource.php
  src/app/Http/Controllers/AccountSettingController.php
  src/app/Http/Controllers/LoginController.php
  src/app/Http/Controllers/RegisterController.php
  src/app/Http/Requests/AccountChangeEmailRequest.php
  src/app/Http/Requests/AccountChangePasswordRequest.php
  src/app/Http/Requests/AccountChangeUsernameRequest.php
  src/app/Http/Requests/RegisterRequest.php
  src/app/Library/Discourse/Api/DiscourseAdminApi.php
  src/app/Library/Discourse/Api/DiscourseUserApi.php
  src/app/Library/Discourse/Authentication/DiscourseLoginHandler.php
  src/app/Library/Discourse/Exceptions/UserNotFound.php
  src/app/Providers/AppServiceProvider.php
  src/app/Rules/DiscourseUsernameRule.php
  src/database/factories/Accounts/AccountFactory.php
  src/database/migrations/2018_03_21_102044_create_user_register_emails.php
  src/database/migrations/2019_07_27_183009_add_username_to_accounts.php
  src/public/assets/js/app.js
  src/resources/lang/en/validation.php
  src/resources/views/front/components/form-error.blade.php
  src/resources/views/front/pages/account/account-settings.blade.php
  src/resources/views/front/pages/account/components/account-sidebar.blade.php
  src/resources/views/front/pages/register/register.blade.php
  src/routes/web.php
  src/tests/Tests/App/Rules/DiscourseUsernameRule_Test.php
Labels: New Feature

#149 Hide image meta
  src/public/assets/css/app.css
  src/resources/sass/pages/_home.scss
Labels: Bug

#151 Release 1.12.0
  src/app/Console/Kernel.php
  src/app/Entities/Accounts/Models/Account.php
  src/app/Entities/Accounts/Models/AccountEmailChange.php
  src/app/Entities/Accounts/Models/UnactivatedAccount.php
  src/app/Entities/Accounts/Notifications/AccountActivationNotification.php
  src/app/Entities/Accounts/Notifications/AccountEmailChangeVerifyNotification.php
  src/app/Entities/Accounts/Notifications/AccountPasswordResetCompleteNotification.php
  src/app/Entities/Accounts/Notifications/AccountPasswordResetNotification.php
  src/app/Entities/Accounts/Repositories/AccountEmailChangeRepository.php
  src/app/Entities/Accounts/Repositories/AccountLinkRepository.php
  src/app/Entities/Accounts/Repositories/AccountPasswordResetRepository.php
  src/app/Entities/Accounts/Repositories/AccountRepository.php
  src/app/Entities/Accounts/Repositories/UnactivatedAccountRepository.php
  src/app/Entities/Accounts/Resources/AccountResource.php
  src/app/Entities/Environment.php
  src/app/Entities/EnvironmentLevel.php
  src/app/Entities/GameIdentifierType.php
  src/app/Entities/GamePlayerType.php
  src/app/Exceptions/ExceptionHandler.php
  src/app/Http/Actions/AccountSettings/SendEmailForAccountEmailChange.php
  src/app/Http/Actions/AccountSettings/UpdateAccountPassword.php
  src/app/Http/Controllers/AccountSettingController.php
  src/app/Http/Controllers/LoginController.php
  src/app/Http/Controllers/RegisterController.php
  src/app/Http/Middleware/Authenticate.php
  src/app/Http/Requests/AccountChangeEmailRequest.php
  src/app/Http/Requests/AccountChangePasswordRequest.php
  src/app/Http/Requests/AccountChangeUsernameRequest.php
  src/app/Http/Requests/RegisterRequest.php
  src/app/Library/Discourse/Api/DiscourseAdminApi.php
  src/app/Library/Discourse/Api/DiscourseUserApi.php
  src/app/Library/Discourse/Authentication/DiscourseLoginHandler.php
  src/app/Library/Discourse/Exceptions/UserNotFound.php
  src/app/Providers/AppServiceProvider.php
  src/app/Rules/DiscourseUsernameRule.php
  src/composer.lock
  src/database/factories/Accounts/AccountFactory.php
  src/database/migrations/2018_03_21_102044_create_user_register_emails.php
  src/database/migrations/2019_07_27_183009_add_username_to_accounts.php
  src/public/assets/css/app.css
  src/public/assets/js/app.js
  src/resources/lang/en/validation.php
  src/resources/sass/pages/_home.scss
  src/resources/views/front/components/form-error.blade.php
  src/resources/views/front/layouts/master.blade.php
  src/resources/views/front/pages/account/account-settings.blade.php
  src/resources/views/front/pages/account/components/account-sidebar.blade.php
  src/resources/views/front/pages/donate/donate.blade.php
  src/resources/views/front/pages/register/register.blade.php
  src/routes/web.php
  src/tests/Tests/App/Environment_Test.php
  src/tests/Tests/App/Rules/DiscourseUsernameRule_Test.php
Labels: Release

#154 Release 1.12.1
  src/app/Http/Actions/AccountSettings/SendEmailForAccountEmailChange.php
  src/app/Http/Controllers/AccountSettingController.php
Labels: Revision Release

#164 Release 1.13.0
  .codecov.yml
  src/.env.ci
  src/.env.example
  src/app/Entities/Accounts/Models/Account.php
  src/app/Entities/Bans/Models/GameBan.php
  src/app/Entities/Players/Models/MinecraftPlayer.php
  src/app/Http/Controllers/BanlistController.php
  src/app/Library/Discourse/Authentication/DiscoursePayloadValidator.php
  src/composer.json
  src/composer.lock
  src/config/scout.php
  src/database/factories/Bans/GameBanFactory.php
  src/database/seeds/DatabaseSeeder.php
  src/database/seeds/GameBanSeeder.php
  src/public/assets/css/app.css
  src/public/assets/js/app.js
  src/public/assets/js/manifest.js
  src/public/assets/js/vendor.js
  src/resources/sass/app.scss
  src/resources/sass/components/_table.scss
  src/resources/sass/global/_colours.scss
  src/resources/sass/pages/_banlist.scss
  src/resources/views/front/layouts/master.blade.php
  src/resources/views/front/pages/banlist.blade.php
  src/resources/views/vendor/pagination/default.blade.php
  src/routes/web.php
  src/storage/search/.gitignore
  src/storage/search/.gitkeep
  src/tests/Tests/App/Library/Discourse/Authentication/DiscoursePayloadValidator_Test.php
Labels: Release: Minor

#171 Release 1.13.3
  deploy.sh
  src/app/Http/Controllers/Api/DeployController.php
  src/resources/views/front/pages/banlist.blade.php
  src/routes/api.php
  src/routes/web.php
Labels: Release: Revision

#176 Release 1.13.4
  deploy.sh
  src/app/Http/Controllers/Api/DeployController.php
  src/app/Library/RateLimit/storage/SessionTokenStorage.php
  src/public/assets/css/app.css
  src/public/assets/css/navonly.css
  src/public/assets/js/app.js
  src/public/assets/js/manifest.js
  src/public/assets/js/vendor.js
  src/tests/Tests/App/Library/RateLimit/Storage/SessionTokenStorage_Test.php
Labels: Release: Revision

#177 Add config keys for deployment and Discord notifications
  src/app/Http/Controllers/Api/DeployController.php
  src/app/Library/Discord/DiscordNotifyService.php
  src/config/deployment.php
  src/config/services.php
Labels: Bug

#178 Release 1.13.5
  src/app/Http/Controllers/Api/DeployController.php
  src/app/Http/Controllers/BanlistController.php
  src/app/Library/Discord/DiscordNotifyService.php
  src/composer.json
  src/composer.lock
  src/config/deployment.php
  src/config/services.php
  src/storage/debugbar/.gitignore
Labels: Release: Revision

#179 Decode GitHub payload when deploying
  src/app/Http/Controllers/Api/DeployController.php
Labels: Bug

#180 Release 1.13.6
  src/app/Http/Controllers/Api/DeployController.php
Labels: Release: Revision
