Repository projectcitybuild/web, pull requests merged in 2019-08, with the labels that each got.

#146 Clean up Account Settings controller
  src/app/Http/Actions/AccountRegistration/ActivateUnverifiedAccount.php
  src/app/Http/Actions/AccountRegistration/SendRegisterVerificationEmail.php
  src/app/Http/Actions/AccountSettings/SendEmailForAccountEmailChange.php
  src/app/Http/Actions/AccountSettings/UpdateAccountEmail.php
  src/app/Http/Actions/AccountSettings/UpdateAccountUsername.php
  src/app/Http/Controllers/AccountSettingController.php
  src/app/Http/Controllers/RegisterController.php
Labels: Cleanup

#182 Clean up password recovery controller
  src/app/Entities/Accounts/Models/AccountPasswordReset.php
  src/app/Http/Actions/AccountPasswordReset/ResetAccountPassword.php
  src/app/Http/Actions/AccountPasswordReset/SendPasswordResetEmail.php
  src/app/Http/Controllers/BanlistController.php
  src/app/Http/Controllers/DiscourseSSOController.php
  src/app/Http/Controllers/GameAccountController.php
  src/app/Http/Controllers/HomeController.php
  src/app/Http/Controllers/LoginController.php
  src/app/Http/Controllers/PasswordRecoveryController.php
  src/app/Http/Controllers/PasswordResetController.php
  src/resources/views/front/pages/login/login.blade.php
  src/resources/views/front/pages/password-reset/password-reset-form.blade.php
  src/resources/views/front/pages/password-reset/password-reset.blade.php
  src/routes/web.php
Labels: Cleanup

#186 Use existing deployment script on the server
  deploy.sh
  src/app/Http/Controllers/Api/DeployController.php
Labels: Bug

#184 Release 1.14.0
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  deploy.sh
  src/.env.example
  src/app/Entities/Accounts/Models/AccountPasswordReset.php
  src/app/Http/Actions/AccountPasswordReset/ResetAccountPassword.php
  src/app/Http/Actions/AccountPasswordReset/SendPasswordResetEmail.php
  src/app/Http/Actions/AccountRegistration/ActivateUnverifiedAccount.php
  src/app/Http/Actions/AccountRegistration/SendRegisterVerificationEmail.php
  src/app/Http/Actions/AccountSettings/SendEmailForAccountEmailChange.php
  src/app/Http/Actions/AccountSettings/UpdateAccountEmail.php
  src/app/Http/Actions/AccountSettings/UpdateAccountUsername.php
  src/app/Http/Controllers/AccountSettingController.php
  src/app/Http/Controllers/Api/DeployController.php
  src/app/Http/Controllers/BanlistController.php
  src/app/Http/Controllers/DiscourseSSOController.php
  src/app/Http/Controllers/DonationController.php
  src/app/Http/Controllers/GameAccountController.php
  src/app/Http/Controllers/HomeController.php
  src/app/Http/Controllers/LoginController.php
  src/app/Http/Controllers/PasswordRecoveryController.php
  src/app/Http/Controllers/PasswordResetController.php
  src/app/Http/Controllers/RegisterController.php
  src/app/Http/Middleware/Authenticate.php
  src/app/Library/Discourse/Authentication/DiscourseLoginHandler.php
  src/config/discourse.php
  src/database/factories/Accounts/AccountFactory.php
  src/phpunit.xml
  src/resources/views/front/pages/donate/donate-error.blade.php
  src/resources/views/front/pages/donate/donate-thanks.blade.php
  src/resources/views/front/pages/login/login.blade.php
  src/resources/views/front/pages/password-reset/password-reset-form.blade.php
  src/resources/views/front/pages/password-reset/password-reset.blade.php
  src/routes/web.php
  src/tests/Feature/LoginTest.php
  src/tests/TestCase.php
  src/tests/Unit/App/Console/ConsoleKernel_Test.php
  src/tests/Unit/App/Enum_Test.php
  src/tests/Unit/App/Environment_Test.php
  src/tests/Unit/App/Library/Discourse/Authentication/DiscoursePayloadValidator_Test.php
  src/tests/Unit/App/Library/QueryPlayer/GameAdapters/MojangUuidAdapter_Test.php
  src/tests/Unit/App/Library/QueryPlayer/PlayerQueryHandler_Test.php
  src/tests/Unit/App/Library/QueryServer/GameAdapters/MinecraftQueryAdapter_Test.php
  src/tests/Unit/App/Library/QueryServer/ServerQueryHandler_Test.php
  src/tests/Unit/App/Library/RateLimit/Storage/FileTokenStorage_Test.php
  src/tests/Unit/App/Library/RateLimit/Storage/MemoryTokenStorage_Test.php
  src/tests/Unit/App/Library/RateLimit/Storage/SessionTokenStorage_Test.php
  src/tests/Unit/App/Library/RateLimit/TokenBucket_Test.php
  src/tests/Unit/App/Library/Recaptcha/RecaptchaRule_Test.php
  src/tests/Unit/App/Rules/DiscourseUsernameRule_Test.php
  src/tests/Unit/App/Services/Login/LogoutService_Test.php
  src/tests/Unit/App/Services/PlayerBans/PlayerBanService_Test.php
  src/tests/Unit/App/Services/PlayerBans/ServerKeyAuthService_Test.php
  src/tests/Unit/App/Services/PlayerLookup/PlayerLookupService_Test.php
  src/tests/Unit/App/Services/Queries/ServerQueryService_Test.php
Labels: Release: Minor

#81 New Minecraft authentication flow
  src/app/Entities/Accounts/Models/Account.php
  src/app/Entities/Accounts/Models/AccountLink.php
  src/app/Entities/Accounts/Models/AccountPasswordReset.php
  src/app/Entities/Accounts/Models/UnactivatedAccount.php
  src/app/Entities/Bans/Models/GameBan.php
  src/app/Entities/Bans/Models/GameBanLog.php
  src/app/Entities/Bans/Models/GameUnban.php
  src/app/Entities/Donations/Models/Donation.php
  src/app/Entities/Groups/Models/Group.php
  src/app/Entities/Payments/Models/AccountPayment.php
  src/app/Entities/Players/Models/MinecraftAuthCode.php
  src/app/Entities/Players/Models/MinecraftPlayer.php
  src/app/Entities/Players/Models/MinecraftPlayerAlias.php
  src/app/Entities/ServerKeys/Models/ServerKey.php
  src/app/Entities/Servers/Models/Server.php
  src/app/Entities/Servers/Models/ServerCategory.php
  src/app/Entities/Servers/Models/ServerStatus.php
  src/app/Entities/Servers/Models/ServerStatusPlayer.php
  src/app/Entities/Warnings/Models/GameWarning.php
  src/app/Http/Controllers/Api/MinecraftAuthTokenController.php
  src/app/Http/Controllers/Api/TempMinecraftController.php
  src/app/Http/Controllers/MinecraftPlayerLinkController.php
  src/database/migrations/2019_05_26_081858_create_minecraft_auth_codes.php
  src/resources/views/front/pages/minecraft-auth/complete.blade.php
  src/resources/views/front/pages/minecraft-auth/error.blade.php
  src/routes/api.php
  src/routes/web.php
Labels: New Feature

#189 Remove closure routes
  src/routes/web.php
Labels: Bug

#190 Release 1.15.0
  src/app/Entities/Accounts/Models/Account.php
  src/app/Entities/Accounts/Models/AccountLink.php
  src/app/Entities/Accounts/Models/AccountPasswordReset.php
  src/app/Entities/Accounts/Models/UnactivatedAccount.php
  src/app/Entities/Bans/Models/GameBan.php
  src/app/Entities/Bans/Models/GameBanLog.php
  src/app/Entities/Bans/Models/GameUnban.php
  src/app/Entities/Donations/Models/Donation.php
  src/app/Entities/Groups/Models/Group.php
  src/app/Entities/Payments/Models/AccountPayment.php
  src/app/Entities/Players/Models/MinecraftAuthCode.php
  src/app/Entities/Players/Models/MinecraftPlayer.php
  src/app/Entities/Players/Models/MinecraftPlayerAlias.php
  src/app/Entities/ServerKeys/Models/ServerKey.php
  src/app/Entities/Servers/Models/Server.php
  src/app/Entities/Servers/Models/ServerCategory.php
  src/app/Entities/Servers/Models/ServerStatus.php
  src/app/Entities/Servers/Models/ServerStatusPlayer.php
  src/app/Entities/Warnings/Models/GameWarning.php
  src/app/Http/Controllers/Api/MinecraftAuthTokenController.php
  src/app/Http/Controllers/Api/TempMinecraftController.php
  src/app/Http/Controllers/MinecraftPlayerLinkController.php
  src/database/migrations/2019_05_26_081858_create_minecraft_auth_codes.php
  src/resources/views/front/pages/banlist.blade.php
  src/resources/views/front/pages/minecraft-auth/complete.blade.php
  src/resources/views/front/pages/minecraft-auth/error.blade.php
  src/routes/api.php
  src/routes/web.php
Labels: Release: Minor

#194 Change go to login screen link to sso endpoint
  src/resources/views/front/pages/password-reset/password-reset-success.blade.php
Labels: Bug

#193 Add case if account doesn't have username or forum account
  src/app/Http/Controllers/LoginController.php
Labels: Bug
