Repository projectcitybuild/web, pull requests merged in 2020-12, with the labels that each got.

#295 Fix broken seeders
  app/Entities/Donations/Models/DonationPerk.php
  app/Http/Controllers/DiscourseSSOController.php
  app/Http/Middleware/TrustProxies.php
  app/Library/Discourse/Entities/DiscoursePayload.php
  database/seeders/GameBanSeeder.php
Labels: Bug

#305 [Hotfix] fix backup config class
  .github/workflows/bump-version.yml
  config/backup.php
Labels: Hotfix

#308 Run release action immediately after version bump
  .github/workflows/bump-version.yml
  .github/workflows/changelog-config.json
  .github/workflows/create-release.yml
Labels: CI/CD

#309 Delete unneeded ImportEssentialsBanCommand
  app/Console/Commands/ImportEssentialsBansCommand.php
  app/Console/Kernel.php
Labels: Cleanup

#310 Fix empty server categories appearing in the server feed
  app/Entities/Servers/Repositories/ServerCategoryRepository.php
  app/Entities/Servers/Repositories/ServerCategoryRepositoryCache.php
  app/Http/Composers/MasterViewComposer.php
  app/Providers/AppServiceProvider.php
Labels: Bug

#311 Add master and release sync action
  .github/workflows/changelog-config.json
  .github/workflows/sync-release-and-master.yml
Labels: CI/CD

#307 MFA
  app/Console/Kernel.php
  app/Entities/Accounts/Models/Account.php
  app/Entities/Accounts/Notifications/AccountMfaBackupCodeRegeneratedNotification.php
  app/Entities/Accounts/Notifications/AccountMfaBackupCodeUsedNotification.php
  app/Entities/Accounts/Notifications/AccountMfaDisabledNotification.php
  app/Entities/Accounts/Notifications/AccountMfaEnabledNotification.php
  app/Entities/Players/Repositories/MinecraftPlayerRepository.php
  app/Entities/Servers/Repositories/ServerCategoryRepository.php
  app/Http/Controllers/Api/MinecraftAuthTokenController.php
  app/Http/Controllers/LoginController.php
  app/Http/Controllers/MfaBackupController.php
  app/Http/Controllers/MfaLoginGateController.php
  app/Http/Controllers/ReauthController.php
  app/Http/Controllers/Settings/AccountSecurityController.php
  app/Http/Controllers/Settings/Mfa/DisableMfaController.php
  app/Http/Controllers/Settings/Mfa/FinishMfaController.php
  app/Http/Controllers/Settings/Mfa/ResetBackupController.php
  app/Http/Controllers/Settings/Mfa/SetupMfaController.php
  app/Http/Controllers/Settings/Mfa/StartMfaController.php
  app/Http/Kernel.php
  app/Http/Middleware/ActiveMfaSession.php
  app/Http/Middleware/MfaGate.php
  app/Library/Backup/BackupHasFailed.php
  app/Library/Backup/BackupWasSuccessful.php
  app/Library/Backup/CleanupHasFailed.php
  app/Library/Backup/CleanupWasSuccessful.php
  app/Library/Backup/HealthyBackupWasFound.php
  app/Library/Backup/UnhealthyBackupWasFound.php
  app/Library/Discord/DiscordNotificationFromSlack.php
  app/Library/Discord/DiscordWebhookNotifiable.php
  app/Library/RateLimit/Storage/FileTokenStorage.php
  app/Library/RateLimit/Storage/MemoryTokenStorage.php
  app/Library/RateLimit/Storage/SessionTokenStorage.php
  composer.json
  composer.lock
  config/auth.php
  database/factories/AccountFactory.php
  database/migrations/2020_12_24_163432_add_2fa_fields_to_accounts.php
  resources/sass/app.scss
  resources/sass/components/_card.scss
  resources/sass/components/_input.scss
  resources/sass/pages/_account.2fa.scss
  resources/sass/pages/_account.security.scss
  resources/views/front/components/form-error.blade.php
  resources/views/front/pages/account/account-security.blade.php
  resources/views/front/pages/account/components/account-sidebar.blade.php
  resources/views/front/pages/account/security/2fa-disable.blade.php
  resources/views/front/pages/account/security/2fa-setup.blade.php
  resources/views/front/pages/account/security/backup-refresh-new-code.blade.php
  resources/views/front/pages/account/security/backup-refresh.blade.php
  resources/views/front/pages/login/login.blade.php
  resources/views/front/pages/login/mfa-backup.blade.php
  resources/views/front/pages/login/mfa.blade.php
  resources/views/front/pages/login/reauth.blade.php
  routes/web.php
  tests/Feature/AccountSecurityTest.php
  tests/Feature/MfaBackupTest.php
  tests/Feature/MfaLoginTest.php
  tests/TestCase.php
Labels: Feature

#316 Remove unnecessary test run on PR creation
  .github/workflows/test.yml
Labels: CI/CD

#323 Auto prepare release PR
  .github/workflows/merge-release-into-master.yml
  .github/workflows/open-release-pr.yml
  .github/workflows/sync-release-and-master.yml
Labels: CI/CD
